### ISSUE TITLE
HTTP flooding possible ?

### ISSUE THREAD

**Issue by ghost** [sepehrdaddev/Xerxes#32]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by sepehrdaddev** [comment]
@masquerade-S yes,
infact http/https is one of the 18 vectors that this supports

**Comment by darknodi** [comment]
bro  can I ddossing an Internet Service Provider Address with multiple port. tell me. thank . 

ip 23.3.3.3. 80 22 2000 23 @sepehrdaddev

**Comment by darknodi** [comment]
@sepehrdaddev @GinjaChris 

xerxes the most powerful scripting coordinated flooding internet service provider address bandwidths.

The most record to you bro. is to make. 

Only for flooding bandwidth of an external INTERNET SERVICE PROVIDER address, by an port. or multi port. 

EXAMPLE . 
IP BY ISP FROM PUBLIC IP THAT IS OFFERED FROM ISP COMPANY scanned by Angry Scanner. 
92.119.236.76 

pentmenu 92.119.236.76 23 200 22 44 

or XERXES with this coordination 92.119.236.1/254 22 or 80 or 23 

this is that I would want. Will be a genius in the world is you make this. 

like 

sh ./xerxes 92.119.236.1/254 with an port. 22 or 80. or. 23 etc.


make this coordination. please. 

./xerxes 92.119.236.1/254  22 
 or 23 or 80 .

and 
./xerxes 92.119.236.1/254 -b bandwidth -t threads 100

**Comment by sepehrdaddev** [comment]
@darknodi 
Thank you for your contributing to this project.
I'm currently working on new vectors and multi vector support and your requested feature will become a part of the project in the upcoming releases so be patient.

**Comment by darknodi** [comment]
@sepehrdaddev graciously.

**Comment by darknodi** [comment]
@sepehrdaddev mobaxterm an powerful interactive for windows 7/10 with multi interactions command line interpreter, the terminal is like ubuntu. that integrates package products linux by upload from https://mobaxterm.mobatek.net/plugins.html or manually from interface. or apt-get from cli bash-ubuntu. :)

you can make integrated the script as the plugin for mobaxterm. like mxt3. or just file.c mobaxterm. have gcc. have from toolbox network scanner. port scanner. 1/254 to 65555. with icons.
Is an 
![1](https://user-images.githubusercontent.com/53880499/63727282-25e9b680-c860-11e9-9060-7a11c2a68f39.PNG)
![2](https://user-images.githubusercontent.com/53880499/63727283-25e9b680-c860-11e9-9fe3-1430baeb4fd6.PNG)
![3](https://user-images.githubusercontent.com/53880499/63727284-25e9b680-c860-11e9-8715-cc5da8fb9dbd.PNG)
![4](https://user-images.githubusercontent.com/53880499/63727285-25e9b680-c860-11e9-9b90-2d5ec3851ec2.PNG)
![6](https://user-images.githubusercontent.com/53880499/63727287-26824d00-c860-11e9-98bb-d9882f3be4b5.PNG)
![7](https://user-images.githubusercontent.com/53880499/63727288-26824d00-c860-11e9-8b8f-0b149eef3933.PNG)
![8](https://user-images.githubusercontent.com/53880499/63727289-271ae380-c860-11e9-8f0f-117d8145f5f6.PNG)
![9](https://user-images.githubusercontent.com/53880499/63727291-271ae380-c860-11e9-8b08-947ef9076d9e.PNG)
![11](https://user-images.githubusercontent.com/53880499/63727295-271ae380-c860-11e9-9b57-c25f413fb160.PNG)
![12](https://user-images.githubusercontent.com/53880499/63727296-27b37a00-c860-11e9-899c-2a6507ee4408.PNG)

**Comment by darknodi** [comment]
@sepehrdaddev you can download mobaxterm free. or nulled from 

[https://www.teamos-hkrg.com/index.php?threads/mobaxterm-professional-edition-10-6-build-3648-portable.58648/](url)

**Comment by sepehrdaddev** [comment]
@darknodi please don't flood this comment section with unnecessary information,
Also This project is currently a linux only technology.
so you will have to wait a bit till it will be ported to windows.
or you can port it to windows and submit pull requests.

Thanks for your contribution to this project

**Comment by darknodi** [comment]
@sepehrdaddev 
![25](https://user-images.githubusercontent.com/53880499/63728173-043dfe80-c863-11e9-8940-5b731b6037f5.PNG)
![667](https://user-images.githubusercontent.com/53880499/63728174-043dfe80-c863-11e9-9f2f-4a0932ce782c.PNG)

To keep most popular for executing script install integrates plugins for keeping CLI formarly regurlarly. without package dist

**Comment by darknodi** [comment]
@sepehrdaddev ok :)

**Comment by darknodi** [comment]
@sepehrdaddev make the script with installation shell. for readed from input ( like pentdos :) 

PentDoS a multi-threading toolkit coordination. 

your folder ( pentdos ) pathed/located on computer ( files ) multi-threading.c pcap.c (cpp ) etcetc.
and. pentdos.sh 

cd pentbox

chmod +x install.sh

./install.sh

cd phonia

chmod +x uninstall.sh

./uninstall.sh

make in the starting this argumental usage EXAMPLE

pentdos 

optional arguments:
  -h,            show this help message and exit
  -l,  Local Area Network without port 192.1.1/254 -b
  -i , Internet Service Provider 
  -p, Port
  -t, Threading
  -b Bandwidth threading

  --info                Show PentDoS Toolkit credits.

Usage 1 for lan without port Like SelfishNet that work with winpcap.
( pentdos 192.168.1.1/254 -b ) 

usage2 for ISP with port like Sprut with multi-threading undisconnection (unpaused) 

this is an ip pinged from an domain website ( adisa.gov.al ) 

[ pentdos -i 134.0.41.206    -p 80 -t 10 [ this coordination ) if for threading website.... only with a port.  
Like SPRUT. 

[ pentdos -i 134.0.41.1/254 -p 80 [ this coordination with ranged ip ] 
 is for threading multi-ranged connections of an ISP to a port for websites, ssh, telnet, p2p ] 

[ pentdos -i 134.0.41.1/254 -b [ this coordination is like Selfishnet but out of the LAN, that threading multi-connection of an internet service provider. 

GAMES NET 1 
GAMES NET 2
INTERNET 1 
INTERNET 2 

without arguments 

**pentdos for a website or for a connection server** > 
pentdos 134.0.41.206 80 10 ( with a port, with thread ) :) 

**pentdos for multi-ranged connection to a port website or server**
root@ubuntu: 
pentdos  134.0.41.1/254 80 ( multi-ranged connection to the port website or server ) 

**pentdos for multi-ranged threading out of the LAN to an public IP.**
pentdos 134.0.41.1/254 ( multi threading of public ip from an ISP, out of the LAN. 
pentdos 192.168.1.2/254 (with 192.   like selfishnet ) 

Sprut I like because. When thread a website, from a port, and when website is offline, sprut does not disconnect threading to the website, only when you make stop threading, the website, returnes. 

![ff](https://user-images.githubusercontent.com/53880499/63760137-0f267c80-c8bf-11e9-850a-d086146f832e.PNG)

![2344](https://user-images.githubusercontent.com/53880499/63762261-cd97d080-c8c2-11e9-83e2-a798ca4071b9.PNG)
